name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Add SSH Key to deploy to the Droplet
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      # Step 3: Copy files to the Droplet
      - name: Copy files via SCP
        run: |
          scp -r -o StrictHostKeyChecking=no ./ git_user@${{ secrets.DO_SERVER_IP }}:/var/www/apertureapi  # Change the destination directory

      # Step 4: SSH into Droplet and restart your application or server
      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no git_user@${{ secrets.DO_SERVER_IP }} << 'EOF'
            cd /var/www/apertureapi  # Change to your directory
            # Step 5: Set up virtual environment (if using one)
            python3 -m venv venv
            source venv/bin/activate

            # Step 6: Install dependencies
            pip install -r requirements.txt

            # Step 7: Restart the application
            # If you're using Gunicorn with systemd:
            sudo systemctl restart gunicorn

            # OR if you run it directly:
            # pkill -f gunicorn
            # gunicorn --workers 3 app:app -b 0.0.0.0:8000 --daemon
          EOF
