name: Python Test

on:
  pull_request:
    branches:
      - main  # Run tests on pull requests to main branch
      - develop  # Run tests on pull requests to develop branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your desired Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Or use Pipfile if you're using pipenv

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest app/ # Run pytest (adjust if using a different framework)
